name: Next js build with caching & artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.1

      - name: Setup Node JS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependences
        run: npm install

      - name: Build Next js ap
        run: npm run build

      - name: Upload build on artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: nextjs-build
          path: .next/
        
        
